### ISSUE TITLE
code/design review: project downloaden + runnen

### ISSUE THREAD

**Issue by wingsvn** [Annevd/your-tribe-for-life-profile-card#20]
Ik heb je project gecloned en in de terminal de volgende commands uitgevoerd, maar kon je project niet runnen: 
`cd frontend' en `npm install`. De volgende problemen kwamen voor:
* cd: no such file or directory: frontend
* npm install --> npm can't find a file.

Ik weet niet of dit nu aan mij ligt of niet, ik zou het nog even controleren ^^

In je readme staat verder nog niet welke stappen ik moet ondernemen om je project te kunnen downloaden en runnen. Voeg dit nog even toe :)

**Comment by Annevd** [comment]
In de ReadME staan nu uitgebreide instructies over de installatie van mijn project. Ik heb dit laten testen door een klasgenoot, #24 ,  en dit ging goed!

Wat ik denk dat er mis ging is dat we `npm install` hadden uitgevoerd voordat we `cd frontend`  hadden gedaan. Hopelijk gaat het in de toekomst nu goed!
