### ISSUE TITLE
Datum

### ISSUE THREAD

**Issue by Hadil66** [Annevd/your-tribe-for-life-profile-card#22]
Je kan voor de datum ook een `time` tag gebruiken. 

https://github.com/Annevd/your-tribe-for-life-profile-card/blob/aceff50f5a1157ffaf55dafdc2c3b5e9721e01ff/frontend/src/routes/%2Bpage.svelte#L59

[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time)

**Comment by Annevd** [comment]
"The <time> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a specific period in time. It may include the datetime attribute to translate dates into machine-readable format, allowing for better search engine results or custom features such as reminders."

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

Omdat in dit geval het niet nodig is voor deze datum om machine-readable, of toevoeg baar aan een agenda te zijn, hoeft het niet per se in een `<time>` tag.

Wel super handig, ik kende dit element nog niet. Dankjewel!
