### ISSUE TITLE
code / design review: line-height + consistentie

### ISSUE THREAD

**Issue by wingsvn** [Annevd/your-tribe-for-life-profile-card#23]
Hele leuke profile card! Goed dat je de informatie via custom data hebt kunnen ophalen. Ook hele toffe sterretjes die zo om je kaartje heen draaien.

feedback: misschien je text in je bio een grotere line-height geven van minimaal 1.2. Dat maakt het makkelijker leesbaarder. 
Verder zou ik qua design nog kijken of je de logo's van de linkjes naar andere websites dezelfde dikte kunt geven.

https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#accessibility

**Comment by Annevd** [comment]
## 17-9 Line height + Logo's fix

Ik heb de `line-height: 1.2;` aangepast, en de linkjes hopelijk wat consistenter gemaakt!

<img width=400 src="https://github.com/user-attachments/assets/fda1973b-89c1-4de2-ad43-2392f67c66fd">

[commit](https://github.com/Annevd/your-tribe-for-life-profile-card/commit/eeccd31fc68c4f4ae3d1139255a6cde3687428c7)

**Comment by wingsvn** [comment]
Je hebt netjes de line-height verhoogd naar 1.2 voor een betere leesbaarheid en de diktes van de logo's consistenter gemaakt. Top dat je dit hebt verwerkt! Mijn issue kan gesloten worden :)
