### ISSUE TITLE
code design review

### ISSUE THREAD

**Issue by lisavanmansom** [Annevd/your-tribe-for-life-profile-card#25]
Ik heb de uitleg van de installatie gevolgd, alles was hierdoor duidelijk en het werkte ook. Het design ziet er netjes uit.

### Kleurcontrast

Er zijn 2 achtergrondelementen die tekst zijn die niet een juist colorcontrast hebben. Hier zou je nog naar kunnen kijken.  (tekst: "frontend student")

<img width="300" alt="Scherm­afbeelding 2024-09-16 om 11 19 08" src="https://github.com/user-attachments/assets/dd5377ac-b363-42b1-977f-9e74df3baf02">
<img width="300" alt="Scherm­afbeelding 2024-09-16 om 11 17 22" src="https://github.com/user-attachments/assets/59e23446-9ac9-4078-9eee-b3c32bca5a49">

**Comment by Annevd** [comment]
## 17-9 Kleurencontrast Fix

Ik heb de kleurcontrasten van de accentkleuren veranderd tot waar het geslaagd is voor de minimum contrastverhouding. Omdat het hier gaat om niet-tekstuele elementen en de tekst "Student FDND" puur decoratief is, voldoet dit aan de eisen. 

### Resultaat accentkleur 1
<img width=300 src="https://github.com/user-attachments/assets/63c25e23-de16-47df-969e-27bbe9678100">

### Resultaat accentkleur 2
<img width=300 src="https://github.com/user-attachments/assets/2e747ae4-9c5f-4fda-a5ff-b515a0c7f0f8">

### Resultaat accentkleur 3
<img width=300 src="https://github.com/user-attachments/assets/f0cb8d68-27ce-4956-a948-014296ddc0a2">

**Comment by lisavanmansom** [comment]
Wow doe je goed!
